# Generated by Django 3.1.5 on 2021-03-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='subject',
        ),
        migrations.AddField(
            model_name='staff',
            name='subjectTeaching',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
